// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct manages the application logic
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GenerateRenovationAdvice sends a request to the local Ollama API to generate renovation advice based on telemetry data
 * @param {string} telemetryJSON
 * @returns {$CancellablePromise<string>}
 */
export function GenerateRenovationAdvice(telemetryJSON) {
    return $Call.ByID(4250304363, telemetryJSON);
}

/**
 * ProcessModel triggers the Docker pipeline for USD analysis or bypasses for GLB
 * @param {string} absolutePath
 * @param {string} bpp
 * @returns {$CancellablePromise<string>}
 */
export function ProcessModel(absolutePath, bpp) {
    return $Call.ByID(4139425631, absolutePath, bpp);
}

/**
 * SelectFile prompts the user with a system dialog to pick a 3D asset
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(2427571203);
}
