# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline/pipeline.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pipeline/pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17pipeline/pipeline.proto\x12\x08pipeline\"\\\n\x13ProcessModelRequest\x12\x15\n\rabsolute_path\x18\x01 \x01(\t\x12\x16\n\x0etarget_bitrate\x18\x02 \x01(\x05\x12\x16\n\x0etraining_steps\x18\x03 \x01(\x05\"\x95\x01\n\x14ProcessModelResponse\x12\x13\n\x0bupdate_type\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x63urrent_step\x18\x03 \x01(\x05\x12\x13\n\x0btotal_steps\x18\x04 \x01(\x05\x12\x14\n\x0c\x63urrent_loss\x18\x05 \x01(\x02\x12\x16\n\x0etelemetry_json\x18\x06 \x01(\t2e\n\x12NtcPipelineService\x12O\n\x0cProcessModel\x12\x1d.pipeline.ProcessModelRequest\x1a\x1e.pipeline.ProcessModelResponse0\x01\x42\x10Z\x0e./pipeline_rpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline.pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016./pipeline_rpc'
  _globals['_PROCESSMODELREQUEST']._serialized_start=37
  _globals['_PROCESSMODELREQUEST']._serialized_end=129
  _globals['_PROCESSMODELRESPONSE']._serialized_start=132
  _globals['_PROCESSMODELRESPONSE']._serialized_end=281
  _globals['_NTCPIPELINESERVICE']._serialized_start=283
  _globals['_NTCPIPELINESERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
