// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct manages the application logic
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GenerateRenovationAdvice sends a request to the local Ollama API to generate renovation advice based on telemetry data
 */
export function GenerateRenovationAdvice(telemetryJSON: string): $CancellablePromise<string> {
    return $Call.ByID(4250304363, telemetryJSON);
}

/**
 * ProcessModel triggers the Docker pipeline for USD analysis or bypasses for GLB
 */
export function ProcessModel(absolutePath: string, bpp: string): $CancellablePromise<string> {
    return $Call.ByID(4139425631, absolutePath, bpp);
}

/**
 * SelectFile prompts the user with a system dialog to pick a 3D asset
 */
export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(2427571203);
}
