// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pipeline/pipeline.proto

package pipeline_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbsolutePath  string                 `protobuf:"bytes,1,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	TargetBitrate int32                  `protobuf:"varint,2,opt,name=target_bitrate,json=targetBitrate,proto3" json:"target_bitrate,omitempty"`
	TrainingSteps int32                  `protobuf:"varint,3,opt,name=training_steps,json=trainingSteps,proto3" json:"training_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessModelRequest) Reset() {
	*x = ProcessModelRequest{}
	mi := &file_pipeline_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessModelRequest) ProtoMessage() {}

func (x *ProcessModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessModelRequest.ProtoReflect.Descriptor instead.
func (*ProcessModelRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessModelRequest) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *ProcessModelRequest) GetTargetBitrate() int32 {
	if x != nil {
		return x.TargetBitrate
	}
	return 0
}

func (x *ProcessModelRequest) GetTrainingSteps() int32 {
	if x != nil {
		return x.TrainingSteps
	}
	return 0
}

type ProcessModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "info", "progress", "result", "error"
	UpdateType string `protobuf:"bytes,1,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Used when update_type == "progress"
	CurrentStep int32   `protobuf:"varint,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	TotalSteps  int32   `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	CurrentLoss float32 `protobuf:"fixed32,5,opt,name=current_loss,json=currentLoss,proto3" json:"current_loss,omitempty"`
	// Used when update_type == "result"
	TelemetryJson string `protobuf:"bytes,6,opt,name=telemetry_json,json=telemetryJson,proto3" json:"telemetry_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessModelResponse) Reset() {
	*x = ProcessModelResponse{}
	mi := &file_pipeline_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessModelResponse) ProtoMessage() {}

func (x *ProcessModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessModelResponse.ProtoReflect.Descriptor instead.
func (*ProcessModelResponse) Descriptor() ([]byte, []int) {
	return file_pipeline_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessModelResponse) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *ProcessModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessModelResponse) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *ProcessModelResponse) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ProcessModelResponse) GetCurrentLoss() float32 {
	if x != nil {
		return x.CurrentLoss
	}
	return 0
}

func (x *ProcessModelResponse) GetTelemetryJson() string {
	if x != nil {
		return x.TelemetryJson
	}
	return ""
}

var File_pipeline_pipeline_proto protoreflect.FileDescriptor

const file_pipeline_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x17pipeline/pipeline.proto\x12\bpipeline\"\x88\x01\n" +
	"\x13ProcessModelRequest\x12#\n" +
	"\rabsolute_path\x18\x01 \x01(\tR\fabsolutePath\x12%\n" +
	"\x0etarget_bitrate\x18\x02 \x01(\x05R\rtargetBitrate\x12%\n" +
	"\x0etraining_steps\x18\x03 \x01(\x05R\rtrainingSteps\"\xdf\x01\n" +
	"\x14ProcessModelResponse\x12\x1f\n" +
	"\vupdate_type\x18\x01 \x01(\tR\n" +
	"updateType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\x05R\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\x12!\n" +
	"\fcurrent_loss\x18\x05 \x01(\x02R\vcurrentLoss\x12%\n" +
	"\x0etelemetry_json\x18\x06 \x01(\tR\rtelemetryJson2e\n" +
	"\x12NtcPipelineService\x12O\n" +
	"\fProcessModel\x12\x1d.pipeline.ProcessModelRequest\x1a\x1e.pipeline.ProcessModelResponse0\x01B\x10Z\x0e./pipeline_rpcb\x06proto3"

var (
	file_pipeline_pipeline_proto_rawDescOnce sync.Once
	file_pipeline_pipeline_proto_rawDescData []byte
)

func file_pipeline_pipeline_proto_rawDescGZIP() []byte {
	file_pipeline_pipeline_proto_rawDescOnce.Do(func() {
		file_pipeline_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_pipeline_proto_rawDesc), len(file_pipeline_pipeline_proto_rawDesc)))
	})
	return file_pipeline_pipeline_proto_rawDescData
}

var file_pipeline_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pipeline_pipeline_proto_goTypes = []any{
	(*ProcessModelRequest)(nil),  // 0: pipeline.ProcessModelRequest
	(*ProcessModelResponse)(nil), // 1: pipeline.ProcessModelResponse
}
var file_pipeline_pipeline_proto_depIdxs = []int32{
	0, // 0: pipeline.NtcPipelineService.ProcessModel:input_type -> pipeline.ProcessModelRequest
	1, // 1: pipeline.NtcPipelineService.ProcessModel:output_type -> pipeline.ProcessModelResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pipeline_pipeline_proto_init() }
func file_pipeline_pipeline_proto_init() {
	if File_pipeline_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_pipeline_proto_rawDesc), len(file_pipeline_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pipeline_pipeline_proto_goTypes,
		DependencyIndexes: file_pipeline_pipeline_proto_depIdxs,
		MessageInfos:      file_pipeline_pipeline_proto_msgTypes,
	}.Build()
	File_pipeline_pipeline_proto = out.File
	file_pipeline_pipeline_proto_goTypes = nil
	file_pipeline_pipeline_proto_depIdxs = nil
}
