---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgA1Xuxjh+kais+gKnkweABOhE7E96ruaft+ouovRLRaHBY3RWyEuqoBoqjkLLlSTYKP8DePGjluF1Z61e44n1YOdp2t7f/piDxzVtKdqXjZm18IYwYmpxoyVmlY0OScDXU3CO3T88XOfDl2V6IqS1Xgh7WwUKL7+NepX6uB4hI5lOsV10gIGNaszpj4t09QrNH6rpi0cWWAx+FFdj3mdvribYC9dtdstEcfpLKT1BtBkU6cXm6M5MBUVlU2Z9N77fzrBkeLkfjF3tIRwMuw8oyxMPjuAGJJdq4WsYc1LYYRGyUDBNkMRy5dUAD5WVRwxqJDe2i+raHji/e5uNMiMIyjrZgaUF7Q2reGX4g1SYHaFWG4ApD/lOd4YPBRk2g9hDW8VWB46W8FFc5bz9b10F56SjRr9dRA4RFHrwpOIwAgUI+AwEMa66h5p2TvbkUlcoLaOM97LwgS0KgpmfZ+dm8uu07kDVufsteQAc9gxV13pRni4NR46kjopZxbXWkAy3Q3t4+Rvlw5ulPCbJOuPzwzKLTvStaL6G7eZVCnneqW04kzfNm6ykDIK2FVo4iSaBt6xL0842zHYJ3mLxlm0KBepQYOtt++6PPHaBzyslxzRrBhgKOfqgaTPJBI0D7eSmWlac9m5zF06ZHUnhpZeX+DQRlSCSWHLynoPwWzfIrOy7ndE5VDh3QcbdaD1q0QfcP9c0kLd0ucogN98VyBkSzOR3kXQ4Aj
    rootUser: AgAWx3zxF9xDnbgWqoAHI566B0xpsmO/QuJrL6Yrv1aOJjx3KG2v0aXNm8/dCYioswYciqIJsCARjJ8iCPBujigX8TmmmGgVIg4MASXgeD3sTjUOOnCxwgF2rwlSpZRxnx9Tqmz3eBgCpxEpNNJKoNJU3r7nWzF3BX0p10OgogsdhRTEOzmA7syP4XIX5IBL09V9/YscYMRG0qiSYxoBZgECSUyH+LitC39cMxSKtLB4gdl/asSl393SG9K+6ZlwT2c9rDMJehJY1RHwSv6DGC5KLTnu3NBmqxbV185QBnf1MMtVjb5N5m/z+8JL6bgpReqK48wxhnjdAzzuM79JRifkA5YDis/lNoT7hIGIzvjb2+SNQesFojEGtTXv3lZV7Bcl8v+G4606KGu4qVAuOgGKBmVgAHazw0WTEJxE6pQ0J2LNcuOoXCCkO9xRgkCKss1uWsRtlODfPOWNEw/75H9aThocPmTJJzS0+s6nG0riOnsdpBATWMgQHa5sJ16rMby/SrQaMknIVBqcyBLruaFJju7gSV/Cj0BEJgBX6CZTccIAw4vmAB3ZA92Tbn6TtSgV8VnTOxrYqh318hvGktZq9lTgm8tnOmHIe86+dur0WkcmOcmj8fRhBCWvZ9TtF1gj7T/r8uXBPVIPtOzG0dhDQLbmvCYc9BHL8dcdYDEBuxDcVpx3JUndouf4kHY2qFWMldNH7A==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
