apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        mode: standalone
        replicas: 1
        rootUser: admin
        rootPassword: Nequ3dSecureStore2026!
        buckets:
          - name: raw-scans
            policy: public
          - name: processed-models
            policy: public
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
