# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pipeline import pipeline_pb2 as pipeline_dot_pipeline__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline/pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NtcPipelineServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessModel = channel.unary_stream(
                '/pipeline.NtcPipelineService/ProcessModel',
                request_serializer=pipeline_dot_pipeline__pb2.ProcessModelRequest.SerializeToString,
                response_deserializer=pipeline_dot_pipeline__pb2.ProcessModelResponse.FromString,
                _registered_method=True)


class NtcPipelineServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NtcPipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessModel': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessModel,
                    request_deserializer=pipeline_dot_pipeline__pb2.ProcessModelRequest.FromString,
                    response_serializer=pipeline_dot_pipeline__pb2.ProcessModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.NtcPipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.NtcPipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NtcPipelineService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pipeline.NtcPipelineService/ProcessModel',
            pipeline_dot_pipeline__pb2.ProcessModelRequest.SerializeToString,
            pipeline_dot_pipeline__pb2.ProcessModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
