apiVersion: v1
kind: Service
metadata:
  name: {{ include "nequ3d-core.fullname" . }}
  labels:
    app: {{ include "nequ3d-core.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "nequ3d-core.fullname" . }}
