// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: pipeline/pipeline.proto

package pipeline_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NtcPipelineService_ProcessModel_FullMethodName = "/pipeline.NtcPipelineService/ProcessModel"
)

// NtcPipelineServiceClient is the client API for NtcPipelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NtcPipelineServiceClient interface {
	ProcessModel(ctx context.Context, in *ProcessModelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessModelResponse], error)
}

type ntcPipelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNtcPipelineServiceClient(cc grpc.ClientConnInterface) NtcPipelineServiceClient {
	return &ntcPipelineServiceClient{cc}
}

func (c *ntcPipelineServiceClient) ProcessModel(ctx context.Context, in *ProcessModelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessModelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NtcPipelineService_ServiceDesc.Streams[0], NtcPipelineService_ProcessModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessModelRequest, ProcessModelResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NtcPipelineService_ProcessModelClient = grpc.ServerStreamingClient[ProcessModelResponse]

// NtcPipelineServiceServer is the server API for NtcPipelineService service.
// All implementations must embed UnimplementedNtcPipelineServiceServer
// for forward compatibility.
type NtcPipelineServiceServer interface {
	ProcessModel(*ProcessModelRequest, grpc.ServerStreamingServer[ProcessModelResponse]) error
	mustEmbedUnimplementedNtcPipelineServiceServer()
}

// UnimplementedNtcPipelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNtcPipelineServiceServer struct{}

func (UnimplementedNtcPipelineServiceServer) ProcessModel(*ProcessModelRequest, grpc.ServerStreamingServer[ProcessModelResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessModel not implemented")
}
func (UnimplementedNtcPipelineServiceServer) mustEmbedUnimplementedNtcPipelineServiceServer() {}
func (UnimplementedNtcPipelineServiceServer) testEmbeddedByValue()                            {}

// UnsafeNtcPipelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NtcPipelineServiceServer will
// result in compilation errors.
type UnsafeNtcPipelineServiceServer interface {
	mustEmbedUnimplementedNtcPipelineServiceServer()
}

func RegisterNtcPipelineServiceServer(s grpc.ServiceRegistrar, srv NtcPipelineServiceServer) {
	// If the following call panics, it indicates UnimplementedNtcPipelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NtcPipelineService_ServiceDesc, srv)
}

func _NtcPipelineService_ProcessModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessModelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NtcPipelineServiceServer).ProcessModel(m, &grpc.GenericServerStream[ProcessModelRequest, ProcessModelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NtcPipelineService_ProcessModelServer = grpc.ServerStreamingServer[ProcessModelResponse]

// NtcPipelineService_ServiceDesc is the grpc.ServiceDesc for NtcPipelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NtcPipelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pipeline.NtcPipelineService",
	HandlerType: (*NtcPipelineServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessModel",
			Handler:       _NtcPipelineService_ProcessModel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pipeline/pipeline.proto",
}
